# Generated by Django 3.1.14 on 2023-10-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Accomadation Name')),
                ('description', models.TextField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accomadation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='MyTourUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='PLace Name')),
                ('description', models.TextField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('web', models.URLField(verbose_name='Web Address')),
            ],
        ),
        migrations.CreateModel(
            name='ThingsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('attendees', models.ManyToManyField(blank=True, to='tours.MyTourUser')),
                ('day', models.ManyToManyField(blank=True, related_name='tours', to='tours.Day')),
                ('things_list', models.ManyToManyField(blank=True, default=None, related_name='tours', to='tours.ThingsList')),
            ],
        ),
        migrations.CreateModel(
            name='Sightseeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.place')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='places',
            field=models.ManyToManyField(related_name='days', to='tours.Place'),
        ),
        migrations.AddField(
            model_name='day',
            name='sightseeing',
            field=models.ManyToManyField(related_name='days', to='tours.Sightseeing'),
        ),
    ]
