# Generated by Django 4.2.6 on 2023-10-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0002_tour_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(blank=True, default=None, to='tours.place'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_plan',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='tour',
            name='transports',
            field=models.ManyToManyField(blank=True, default=None, to='tours.transport'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='things_list',
            field=models.ManyToManyField(blank=True, default=None, to='tours.thingslist'),
        ),
    ]
