# Generated by Django 4.2.6 on 2023-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_accommodation_id_alter_mytouruser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
