# Generated by Django 4.2.6 on 2023-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(),
        ),
    ]
