# Generated by Django 4.2.6 on 2023-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(blank=True, to='tours.place'),
        ),
    ]
