# Generated by Django 4.2.6 on 2023-10-23 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0014_place_owner_alter_tour_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTourUser',
        ),
        migrations.AlterField(
            model_name='tour',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
