# Generated by Django 4.2.6 on 2023-10-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0015_delete_mytouruser_alter_tour_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='administrator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
