# Generated by Django 4.2.6 on 2023-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_tour_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
